config/routes.rb
Rails.application.routes.draw do
  resources :colleges
  get 'depts/aboutus'
  get 'depts/contact'
  get 'depts/deptinfo'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #devise_for :users
  root to: "depts#deptinfo"
  resources :depts do
   
   member do
    get 'download_pdf'
    end
  end
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
    resources :depts
    end
    end
    #devise_for :users, controllers: {registrations: 'users/registrations'}
    devise_for :users, controllers: { omniauth_callbacks: "callbacks" }
end

app/models/dept.rb
class Dept < ApplicationRecord
    
    #adding custom validations
    def check_name
        if name.blank?
            errors.add(:base, 'name cannot be blank')
        end
    end
    validate :check_name

    def change_name
        name == 'navya'
    end
    validates :students,presence: true , unless: :change_name
    validates :staff, presence: true, if: Proc.new{ |a| a.books.blank?}
    #after_initialize :method_after_intialization
    after_find :method_after_find
    after_touch :method_after_touch
    #before_save :method_before_save
    #after_save  :method_after_save
    around_save :method_around_save
    after_commit :method_after_commit, on: [:create]
    private
    def method_after_intialization
        puts "calling after intialization"
    end
    def method_after_find
        puts "calling after find method"
    end
    def method_after_touch
        puts "calling after touch method"
    end
    #def method_before_save
        #puts "calling before save"
    #end
    def method_after_save
        puts "calling after save"
    end
    def method_around_save
        puts "calling before save"
        yield
        puts "calling after save"
    end
    def method_after_commit
        puts "calling after commit"
    end
    has_one_attached :main_image
end

app/controllers/api/v1/depts_controller.rb
class Api::V1::DeptsController < ActionController::API
    def index
    depts = Dept.all
    render json: {message: 'OK', depts: depts.as_json(only: [:name, :students, :staff, :books,:created_at])}.to_json, status: 200
    end
    def show
    dept = Dept.find(params[:id])
    if dept
    render json: {message: 'OK', dept: dept}.to_json, status: 200
    else
    render json: {message: 'Error', error: 'Dept not found with the given id'}.to_json, status: 404
    end
    rescue => e
    render json: {message: 'Error', error: e.message }.to_json, status: 500
    end
    def create
    dept = Dept.new(dept_params)
    if dept.save
    render json: {message: 'OK', dept: dept}.to_json, status: :created
    else
    render json: {message: 'Error', error: 'dept couldnt create'}.to_json, status: 404
    end
    end
    private
    def dept_params
    params.require(:dept).permit(:name, :students, :staff, :books)
    end
    end

app/controllers/depts_controller.rb
#without scaffolding
class DeptsController < ApplicationController
    #before_action :filters_load, only: ['edit','update','show','destroy','download_pdf']
    def index
    @depts = if params[:q] && !params[:q].blank?
    Dept.where(name: params[:q])
    else Dept.all
    end
    end
    
    
    def show
        @dept = Dept.find(params[:id])   
    end

    def new
        @dept = Dept.new
    end

    def create
        @dept = Dept.new(dept_params)
        if @dept.save
            DeptMailer.notify_dept_creation(@dept.id).deliver_now
            redirect_to depts_path
        else
            render :new
        end
    end
   def aboutus
    # redirect_to depts_aboutus_path
   end
   def contact
    # redirect_to depts_contact_path
   end
    def edit
        @dept = Dept.find(params[:id])   
    end

    def update
        @dept = Dept.find(params[:id])
        if @dept.update(dept_params)
        redirect_to depts_path
        else
        render :edit
        end
    end
    def download_pdf
        @dept = Dept.find(params[:id])
        send_file("#{Rails.root}/public/sample.pdf",
        filename: "#{@dept.name}.pdf",
        type: "application/pdf")
        end
    def destroy
        @dept = Dept.find(params[:id])
        @dept.destroy
        redirect_to depts_path
    end
        private
        def dept_params
        params.require(:dept).permit(:name,:students,:staff,:books, :main_image)
        end
        # def filters_load
        #     @dept = Dept.find(params[:id])
        # end    

end

app/helpers/depts_helper.rb
module DeptsHelper
end

app/views/depts/_depts.html.erb
<center>
<%= form_for @dept do |f| %>
    <% if @dept.errors.any? %>
    <div id="error_explanation" >
    <h2>
    <%= pluralize(@dept.errors.count, "error") %>
    prohibited this dept from being saved:
    </h2>
    <ul>
    <% @dept.errors.full_messages.each do |message| %>
    <li>
    <%= message %>
    <% end %>
    </ul>
    </div>
    <% end %>
    <div>
    <%= f.label :Name %>
    <br>
    <%= f.text_field :name %>
    <br>
    </div>
    <div>
    <%= f.label :Students%>
    <br>
    <%= f.number_field :students%>
    <br>
    </div>
    <div>
    <%= f.label :Staff %>
    <br>
    <%= f.number_field :staff %>
    <br>
    </div>

    <div>
    <%= f.label :Books %>
    <br>
    <%= f.number_field :books%>
    </div>
    <br>
    <div>
    <%= f.label :main_image %>
    <%= f.file_field :main_image %>
    </div>
    <div>
    <br>
    <%= f.submit %>
    <br>
    </div>
    <% end %>
    
    <br>

    <%= link_to "back", depts_path %>

    </center>

app/views/depts/aboutus.html.erb
<center><img src = "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Hogwarts_model_studio_tour.jpg/250px-Hogwarts_model_studio_tour.jpg" style="width:300px;height:200px;"></center>
<p><h3>
Hogwarts is a coeducational, secondary boarding school, taking children from ages eleven to seventeen. Education at Hogwarts is not compulsory, with some students being home schooled as stated in the seventh book. Rowling initially said there are about one thousand students at Hogwarts. She later suggested around six hundred, while acknowledging that this number was still inconsistent with the small number of people in Harry's year. She further explained that this had resulted from her creating only 40 characters for Harry's year.</h3></p>
<br>
<h3>
<strong>
<center>
<%= link_to "back" ,depts_path %>
</center>
</strong>
</h3>

app/views/depts/contact.html.erb
<%= nav_bar fixed: :bottom, brand: "Hogwarts University" do %>

    <%= menu_group do %>
    
    <%= menu_item "Home", root_path %>
    
    <%= menu_item "About Us", depts_aboutus_path %>
    
    <%= menu_item "Contact", depts_contact_path %>
    
    <%= menu_item "Depts Information", depts_path %>
    
    <% end %>
    
    <% end %>
    
    <br>
    
    <br>
    
    <h3> contact us on facebook and twitter </h3>
    
    <html>
    
    <head>
    
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    
    <style>
    .fa {

padding: 20px;

font-size: 30px;

width: 200px;

text-align: center;

text-decoration: none;

margin: 5px 2px;

}

.fa:hover {

opacity: 0.7;

}

.fa-facebook {

background: #3B5998;

color: white;

}

.fa-twitter {

background: #55ACEE;

color: white;

}

</style>

</head>

<body>

<strong>

<a href="https://www.facebook.com/TheHogwartsSchool/" class="fa fa-facebook"><h5>Hogwarts University</h5></a>

<a href="https://twitter.com/wizardingworld?lang=en" class="fa fa-twitter"><h5>Hogwarts University</h5></a>

</strong>

</body>

</html>

app/views/depts/deptinfo.html.erb
<%= nav_bar static: :bottom, brand: "Hogwarts University" do %>
    <%= menu_group do %>
        <%= menu_item "Home", root_path %>
        <%= menu_item "About Us", depts_aboutus_path %>
        <%= menu_item "Contact", depts_contact_path %>
    <% end %>
    <% end %>
<h4>
<center>
<%= link_to "Here is department list",depts_path %>
</center>
</h4>

app/views/depts/edit.html.erb
<%= render 'depts', dept: @dept %>

app/views/depts/index.html.erb
<center >
<h1 bgcolor='#dddddd'>DEPARTMENTS LIST</h1>
<%= link_to "Enter new department",new_dept_path %>
<br>
<table border="5" border = black bgcolor='#dddddd'>
<thead>
<th>NAME</th>
<th>STUDENTS</th>
<th>STAFF</th>
<th>BOOKS</th>
</thead>
<% @depts.each do |dept| %>
<tr>
<td><%= dept.name %> </td>
<td><%= dept.students %></td>
<td><%= dept.staff %></td>
<td><%= dept.books %></td>
<td>
<td><%= link_to "Edit", edit_dept_path(dept) %></td>
<td><%= link_to "delete", dept_path(dept), method: :delete, data: { confirm: "are u sure"} %></td>
<td><%= link_to "show", dept_path(dept) %></td>
<td><%= link_to "download pdf", download_pdf_dept_path(dept) %></td>
</td>
</tr>
<% end %>
</table>
<br>
<div>
<%= form_with url: depts_path, method: 'get' do |f| %>
Search:
<%= f.text_field :q, value: params[:q],placeholder:'Search department by name' %>
<%= f.submit "search" %>
<% end %>
<%= link_to "main page", depts_path %>
<br>
<%= nav_bar static: :bottom, brand: "Hogwarts University" do %>
    <%= menu_group do %>
        <%= menu_item "Home", root_path %>
        <%= menu_item "About Us", depts_aboutus_path %>
        <%= menu_item "Contact", depts_contact_path %>
    <% end %>
    <% end %>
</div>
</center>

app/views/depts/new.html.erb
<%= render 'depts', dept: @dept %>

app/views/depts/show.html.erb
<table>
<strong>Name:</strong>
<%= @dept.name %>
</p>
<p>
<strong>students:</strong>
<%= @dept.students %>
</p>
<strong>staff:</strong>
<%= @dept.staff %>
</p>
<strong>books:</strong>
<%= @dept.books %>
</p>
<%= image_tag @dept.main_image, width: '100' if @dept.main_image.present? %>
<%= link_to 'Back', :back %>
</table>