config/routes.rb
Rails.application.routes.draw do
  resources :colleges
  get 'depts/aboutus'
  get 'depts/contact'
  get 'depts/deptinfo'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #devise_for :users
  root to: "depts#deptinfo"
  resources :depts do
   
   member do
    get 'download_pdf'
    end
  end
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
    resources :depts
    end
    end
    #devise_for :users, controllers: {registrations: 'users/registrations'}
    devise_for :users, controllers: { omniauth_callbacks: "callbacks" }
end

app/models/college.rb
class College < ApplicationRecord
end

app/controllers/colleges_controller.rb
#for the scaffolding
class CollegesController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_college, only: %i[ show edit update destroy ]

  # GET /colleges or /colleges.json
  def index
    @colleges = College.all
  end

  # GET /colleges/1 or /colleges/1.json
  def show
  end

  # GET /colleges/new
  def new
    @college = College.new
  end

  # GET /colleges/1/edit
  def edit
  end

  # POST /colleges or /colleges.json
  def create
    @college = College.new(college_params)

    respond_to do |format|
      if @college.save
        format.html { redirect_to college_url(@college), notice: "College was successfully created." }
        format.json { render :show, status: :created, location: @college }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @college.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /colleges/1 or /colleges/1.json
  def update
    respond_to do |format|
      if @college.update(college_params)
        format.html { redirect_to college_url(@college), notice: "College was successfully updated." }
        format.json { render :show, status: :ok, location: @college }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @college.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /colleges/1 or /colleges/1.json
  def destroy
    @college.destroy

    respond_to do |format|
      format.html { redirect_to colleges_url, notice: "College was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_college
      @college = College.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def college_params
      params.require(:college).permit(:name, :area)
    end
end

app/helpers/colleges_helper.rb
module CollegesHelper
end

app/views/colleges/_form.html.erb
<%= form_with(model: college) do |form| %>
  <% if college.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(college.errors.count, "error") %> prohibited this college from being saved:</h2>

      <ul>
        <% college.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :area %>
    <%= form.text_field :area %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/colleges/edit.html.erb
<h1>Editing College</h1>

<%= render 'form', college: @college %>

<%= link_to 'Show', @college %> |
<%= link_to 'Back', colleges_path %>

app/views/colleges/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Colleges</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Area</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @colleges.each do |college| %>
      <tr>
        <td><%= college.name %></td>
        <td><%= college.area %></td>
        <td><%= link_to 'Show', college %></td>
        <td><%= link_to 'Edit', edit_college_path(college) %></td>
        <td><%= link_to 'Destroy', college, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New College', new_college_path %>

app/views/colleges/new.html.erb
<h1>New College</h1>

<%= render 'form', college: @college %>

<%= link_to 'Back', colleges_path %>

app/views/colleges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @college.name %>
</p>

<p>
  <strong>Area:</strong>
  <%= @college.area %>
</p>

<%= link_to 'Edit', edit_college_path(@college) %> |
<%= link_to 'Back', colleges_path %>